// dsh-memorix-panel — browser half.
//
// Loaded by the DSH shell as `dsh-memorix-panel/client.js` (see the
// `dsh.client` declaration in package.json). Mounts the Memorix panel twice
// safe:
//
//   1. with dsh-better-sidebar present  → a native right-workbench tab
//      (`ctx.betterSidebar.registerTab`), so the entry lives in the right
//      workspace next to Files / Terminal / …;
//   2. otherwise (or alongside a foreign shell) → a native session-header
//      utility entry whose panel renders in the browser top layer, so no
//      other panel can ever cover it.
//
// All data crosses to the host half through POST /memorix-panel/api.
window.__ModuleLoader__.load({
  id: 'dsh-memorix-panel',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    const React = require('react')
    const h = React.createElement

    // ── copy ───────────────────────────────────────────────────────────────
    // Panel copy follows the shell's active locale through the `locale` service:
    // both dictionaries register under this namespace and every lookup reads the
    // active locale at call time. Simplified Chinese stays the default, so a
    // deployment without the locale service keeps the upstream copy verbatim.

    /** Locale namespace owned by this plugin. */
    const NS = 'dsh-memorix-panel'

    /** Simplified-Chinese copy (upstream wording). */
    const zh = {
      'type.howItWorks': '说明',
      'type.decision': '决策',
      'type.gotcha': '坑',
      'type.discovery': '发现',
      'type.fix': '修复',
      'type.change': '变更',
      'type.why': '缘由',
      'type.tradeoff': '权衡',
      'type.reasoning': '推理',
      'type.probe': '探针',
      'type.request': '请求',
      'type.unknown': '未知',

      'status.active': '活跃',
      'status.resolved': '已解决',
      'status.archived': '已归档',

      'lt.state.approved': '已批准',
      'lt.state.qualified': '已确认',
      'lt.state.candidate': '候选',
      'lt.state.superseded': '已被取代',
      'lt.scope.user': '用户级',
      'lt.scope.project': '项目级',
      'lt.scope.team': '团队级',
      'lt.kind.semantic': '事实',
      'lt.kind.procedural': '流程',
      'lt.kind.episodic': '事件',

      'copy.copied': '已复制',
      'copy.copyPrefix': '复制:',
      'copy.copy': '复制',

      'error.badResponse': '接口返回无法解析(HTTP ',

      'reason.panelAction': '面板操作',

      'error.readFailed': '读取 Memorix 失败',
      'error.actionFailed': '操作失败',

      'write.succeeded': ' 成功 → 状态:',

      'error.detailReadFailed': '读取记忆详情失败',
      'error.writeFailed': '写入失败',

      'write.updatedTo': '已更新为「',
      'write.updated': '已更新 ',
      'write.created': '已新建 ',

      'list.clickForBody': '点击查看正文',
      'list.clickForDetail': '点击查看详情',

      'common.untitled': '(无标题)',
      'common.backToList': '← 返回列表',

      'list.noMatches': '没有匹配的记忆',

      'field.title': '标题',
      'field.type': '类型',
      'field.entity': '实体',
      'field.project': '项目',
      'field.status': '状态',
      'field.body': '正文',
      'field.bodyLength': '正文长度',
      'field.facts': '要点',
      'field.concepts': '概念',
      'field.files': '涉及文件',
      'field.source': '来源',
      'field.created': '创建',
      'field.updated': '更新',
      'field.id': '编号',
      'field.valueCategory': '价值类别',
      'field.visibility': '可见性',
      'field.tokens': '令牌',
      'field.revisions': '修订次数',
      'field.session': '会话',
      'field.admissionState': '准入状态',
      'field.scope': '作用域',

      'common.defaultProject': '(默认项目)',
      'common.autoGenerated': '(自动生成)',

      'suffix.chars': ' 字',
      'suffix.items': ' 条',
      'suffix.count': ' 个',

      'project.meta.itemsDot': ' 条 · ',
      'project.meta.active': ' 活跃',

      'compose.confirmTitle': '确认新建记忆',
      'compose.confirmWarning': '写入会调用官方 CLI(`memorix memory store`):新建一条 active 记忆、source=manual。若 topicKey 与已有记忆重复,则会更新那一条而不是新建。',
      'compose.confirmWrite': '确认写入',

      'common.cancel': '取消',

      'compose.writing': '正在写入 Memorix…',
      'compose.title': '新建记忆',
      'compose.titleLabel': '标题 (必填)',
      'compose.titlePlaceholder': '简短描述这条记忆',
      'compose.bodyLabel': '正文 (必填)',
      'compose.bodyPlaceholder': '完整描述:背景、结论、为什么',
      'compose.entityLabel': '实体 entity (可选,默认 general)',
      'compose.factsLabel': '要点 facts (每行一条)',
      'compose.conceptsLabel': '概念 concepts (每行一个)',
      'compose.filesLabel': '涉及文件 (每行一个路径,可选)',
      'compose.topicKeyLabel': 'topicKey (可选;填写且已存在同键时会更新那条)',
      'compose.topicKeyPlaceholder': '如 architecture/auth-model',
      'compose.targetProject': '写入项目',
      'compose.next': '下一步:确认',
      'compose.hint': '要点/概念/文件按"每行一条"提交;条目内的英文逗号会被去掉(CLI 以逗号分隔)。写入后自动跳进新记忆的详情页。',

      'detail.loadingBody': '正在读取记忆正文…',
      'detail.statusDisabled': '该部署已禁用状态写入',
      'detail.statusCurrent': ' · 当前',
      'detail.statusConfirmPrefix': '确认把 #',
      'detail.statusConfirmFrom': ' 从「',
      'detail.statusConfirmTo': '」改为「',
      'detail.statusConfirmSuffix': '」?经官方 CLI 写入(同步检索索引),可随时改回。',
      'detail.statusConfirmButton': '确认修改',
      'detail.section.factsCount': '要点 (',
      'detail.section.commits': '关联提交',
      'detail.section.entities': '关联实体',

      'lt.title': '长期记忆 (',
      'lt.sectionTitle': '长期记忆 · ',
      'lt.loading': '正在读取长期记忆…',
      'lt.loadFailed': '长期记忆读取失败:host 半可能还没加载 long-term 动作(该插件更新了 host 半,需要重启一次 dsh-web)。',
      'lt.empty': '还没有长期记忆。用 memorix memory long-term add --scope user --portability portable … 建立候选,再 qualify + approve 才算生效(候选/已确认都不会进入 Workset)。',
      'lt.noMatches': '没有匹配的长期记忆',
      'lt.stale': '该长期记忆不在当前列表中(可能已被取代或归档),请刷新。',
      'lt.portability': '可携带性',
      'lt.originProject': '起源项目',
      'lt.qualifiedAt': '合格于',
      'lt.approvedAt': '批准于',
      'lt.archivedAt': '归档于',
      'lt.supersededBy': '被取代为',
      'lt.accessCount': '访问次数',
      'lt.evidenceAudit': '证据 / 审计',
      'lt.action.qualify': '确认 (qualify)',
      'lt.action.approve': '批准 (approve)',
      'lt.action.archive': '归档',
      'lt.lifecycle': '生命周期',
      'lt.retired': '该记录已退役(已归档 / 已被取代),没有可用操作。',
      'lt.actionConfirmPrefix': '确认对这条长期记忆执行「',
      'lt.actionConfirmSuffix': '」?状态机:candidate →(qualify)→ qualified →(approve)→ approved;候选与已确认都不进入 Workset,只有 approved 真正生效。',
      'lt.reasonLabel': '理由 reason(会写入审计事件)',
      'lt.actionConfirmButton': '确认执行',
      'lt.working': '正在执行…',
      'lt.applicability': '适用性',
      'lt.content': '内容',
      'lt.tags': '标签',
      'lt.evidenceChain': '证据链',
      'lt.auditEvents': '审计事件',

      'overview.database': '记忆库',
      'overview.dbSize': '库大小',
      'overview.fileMissing': '文件不存在',
      'overview.dbUpdated': '库更新时间',
      'overview.cliVersion': 'CLI 版本',
      'overview.cliMissing': '未检测到(检查 config.bin)',
      'overview.backend': '读取后端',
      'overview.projectRoot': '项目根',
      'overview.chip.memories': '记忆 ',
      'overview.chip.projects': '项目 ',
      'overview.chip.active': '活跃 ',
      'overview.chip.archived': '归档 ',
      'overview.chip.longTerm': '长期记忆 ',
      'overview.chip.miniSkills': '迷你技能 ',
      'overview.chip.sessions': '会话 ',
      'overview.chip.evidenceCards': '证据卡 ',
      'overview.chip.knowledgePages': '知识页 ',
      'overview.newButton': '+ 新建记忆',
      'overview.searchPlaceholder': '搜索标题 / 实体 / 类型…',
      'overview.matches': '命中 ',
      'overview.clearFilters': '清除筛选',
      'overview.projectsTitle': '项目 (',
      'overview.noProjects': 'Memorix 中还没有任何项目记忆',
      'overview.loading': '正在读取 Memorix 记忆…',

      'common.retry': '重试',
      'common.noData': '暂无数据',

      'panel.titleNew': 'Memorix 记忆 · 新建',
      'panel.titleLongTerm': 'Memorix 记忆 · 长期记忆',
      'panel.titleDetail': 'Memorix 记忆 · 详情',
      'panel.titleOverview': 'Memorix 记忆总览',
      'panel.entryTitle': 'Memorix 记忆',
      'panel.entryLabel': '记忆',
      'panel.loading': '读取中…',
      'panel.updatedAt': '更新于 ',
      'panel.refresh': '刷新',
      'panel.close': '关闭',

      'age.justNow': '刚刚',
      'age.minutes': ' 分钟前',
      'age.hours': ' 小时前',
      'age.days': ' 天前',

      'host.read.storeUnavailable': '无法读取 Memorix 存储(需要 Node >= 22.5 或 python3)',
      'host.read.longTermUnavailable': '无法读取长期记忆(需要 Node >= 22.5 或 python3)',
      'host.lt.writeDisabled': '该部署已禁用写入(allowWrite: false)',
      'host.lt.invalidId': '无效的长期记忆 id',
      'host.lt.invalidAction': '无效的动作(仅允许 qualify / approve / archive)',
      'host.lt.projectRootMissing': '未找到项目根路径',
      'host.lt.actionFailed': '长期记忆操作失败',
      'host.lt.noStateFromCli': 'CLI 未返回长期记忆状态',
      'host.memory.notFound': '未找到编号 #{id} 的记忆',
      'host.memory.invalidId': '无效的记忆编号',
      'host.write.statusDisabled': '该部署已禁用状态写入(allowWrite: false)',
      'host.write.invalidStatus': '无效的状态(仅允许 active / resolved / archived)',
      'host.write.projectRootMissing': '未找到该记忆所属项目的根路径',
      'host.write.failed': '写入 Memorix 失败',
      'host.write.notUpdated': 'CLI 未更新该记忆',
      'host.store.disabled': '该部署已禁用新建记忆(allowStore: false)',
      'host.store.emptyTitle': '标题不能为空',
      'host.store.emptyBody': '正文不能为空',
      'host.store.projectRootMissing': '未找到写入目标项目的根路径',
      'host.store.noMemoryFromCli': 'CLI 未返回新建的记忆',
      'host.request.badBody': '请求体解析失败',
      'host.request.unknownAction': '未知操作: {action}',
      'host.hint.noProjectMapping': '缺少 .project-aliases.json 与 last-project-root',
      'host.hint.noLastProjectRoot': '缺少 last-project-root',
      'host.hint.projectNotRegistered': '项目 {projectId} 不在 .project-aliases.json 中',
      'host.hint.cliProject': '项目: {root}',
    }

    /** English copy. */
    const en = {
      'type.howItWorks': 'How it works',
      'type.decision': 'Decision',
      'type.gotcha': 'Gotcha',
      'type.discovery': 'Discovery',
      'type.fix': 'Fix',
      'type.change': 'Change',
      'type.why': 'Why',
      'type.tradeoff': 'Trade-off',
      'type.reasoning': 'Reasoning',
      'type.probe': 'Probe',
      'type.request': 'Request',
      'type.unknown': 'Unknown',

      'status.active': 'Active',
      'status.resolved': 'Resolved',
      'status.archived': 'Archived',

      'lt.state.approved': 'Approved',
      'lt.state.qualified': 'Qualified',
      'lt.state.candidate': 'Candidate',
      'lt.state.superseded': 'Superseded',
      'lt.scope.user': 'User',
      'lt.scope.project': 'Project',
      'lt.scope.team': 'Team',
      'lt.kind.semantic': 'Fact',
      'lt.kind.procedural': 'Procedure',
      'lt.kind.episodic': 'Episode',

      'copy.copied': 'Copied',
      'copy.copyPrefix': 'Copy:',
      'copy.copy': 'Copy',

      'error.badResponse': 'Unparsable API response (HTTP ',

      'reason.panelAction': 'Panel action',

      'error.readFailed': 'Failed to read Memorix',
      'error.actionFailed': 'Action failed',

      'write.succeeded': ' succeeded → state: ',

      'error.detailReadFailed': 'Failed to load memory details',
      'error.writeFailed': 'Write failed',

      'write.updatedTo': 'Updated to "',
      'write.updated': 'Updated ',
      'write.created': 'Created ',

      'list.clickForBody': 'Click to view full text',
      'list.clickForDetail': 'Click for details',

      'common.untitled': '(untitled)',
      'common.backToList': '← Back to list',

      'list.noMatches': 'No matching memories',

      'field.title': 'Title',
      'field.type': 'Type',
      'field.entity': 'Entity',
      'field.project': 'Project',
      'field.status': 'Status',
      'field.body': 'Body',
      'field.bodyLength': 'Body length',
      'field.facts': 'Facts',
      'field.concepts': 'Concepts',
      'field.files': 'Files',
      'field.source': 'Source',
      'field.created': 'Created',
      'field.updated': 'Updated',
      'field.id': 'ID',
      'field.valueCategory': 'Value category',
      'field.visibility': 'Visibility',
      'field.tokens': 'Tokens',
      'field.revisions': 'Revisions',
      'field.session': 'Session',
      'field.admissionState': 'Admission state',
      'field.scope': 'Scope',

      'common.defaultProject': '(default project)',
      'common.autoGenerated': '(auto-generated)',

      'suffix.chars': ' chars',
      'suffix.items': ' items',
      'suffix.count': ' items',

      'project.meta.itemsDot': ' items · ',
      'project.meta.active': ' active',

      'compose.confirmTitle': 'Confirm new memory',
      'compose.confirmWarning': 'Writing calls the official CLI (`memorix memory store`): it creates an active memory with source=manual. If topicKey already exists, that memory is updated instead of creating a new one.',
      'compose.confirmWrite': 'Confirm write',

      'common.cancel': 'Cancel',

      'compose.writing': 'Writing to Memorix…',
      'compose.title': 'New memory',
      'compose.titleLabel': 'Title (required)',
      'compose.titlePlaceholder': 'Short description of this memory',
      'compose.bodyLabel': 'Body (required)',
      'compose.bodyPlaceholder': 'Full description: context, conclusion, rationale',
      'compose.entityLabel': 'Entity (optional, default: general)',
      'compose.factsLabel': 'Facts (one per line)',
      'compose.conceptsLabel': 'Concepts (one per line)',
      'compose.filesLabel': 'Files (one path per line, optional)',
      'compose.topicKeyLabel': 'topicKey (optional; if the key already exists that memory is updated)',
      'compose.topicKeyPlaceholder': 'e.g. architecture/auth-model',
      'compose.targetProject': 'Target project',
      'compose.next': 'Next: confirm',
      'compose.hint': 'Facts / concepts / files are submitted one per line; commas inside an entry are stripped (the CLI splits on commas). After writing, the panel opens the new memory.',

      'detail.loadingBody': 'Loading memory body…',
      'detail.statusDisabled': 'Status writes are disabled in this deployment',
      'detail.statusCurrent': ' · current',
      'detail.statusConfirmPrefix': 'Change #',
      'detail.statusConfirmFrom': ' from "',
      'detail.statusConfirmTo': '" to "',
      'detail.statusConfirmSuffix': '"? Written through the official CLI (keeps the search index in sync); you can change it back anytime.',
      'detail.statusConfirmButton': 'Confirm change',
      'detail.section.factsCount': 'Facts (',
      'detail.section.commits': 'Related commits',
      'detail.section.entities': 'Related entities',

      'lt.title': 'Long-term memory (',
      'lt.sectionTitle': 'Long-term · ',
      'lt.loading': 'Loading long-term memory…',
      'lt.loadFailed': 'Failed to load long-term memory: the host half may not expose the long-term action yet (restart dsh-web once).',
      'lt.empty': 'No long-term memory yet. Create a candidate with `memorix memory long-term add --scope user --portability portable …`, then qualify + approve for it to take effect (candidates and qualified entries never enter the Workset).',
      'lt.noMatches': 'No matching long-term memory',
      'lt.stale': 'This long-term memory is not in the current list (it may be superseded or archived). Refresh to update.',
      'lt.portability': 'Portability',
      'lt.originProject': 'Origin project',
      'lt.qualifiedAt': 'Qualified at',
      'lt.approvedAt': 'Approved at',
      'lt.archivedAt': 'Archived at',
      'lt.supersededBy': 'Superseded by',
      'lt.accessCount': 'Access count',
      'lt.evidenceAudit': 'Evidence / audit',
      'lt.action.qualify': 'Qualify',
      'lt.action.approve': 'Approve',
      'lt.action.archive': 'Archive',
      'lt.lifecycle': 'Lifecycle',
      'lt.retired': 'This record is retired (archived / superseded); no actions available.',
      'lt.actionConfirmPrefix': 'Run "',
      'lt.actionConfirmSuffix': '"? State machine: candidate →(qualify)→ qualified →(approve)→ approved; candidates and qualified entries never enter the Workset — only approved takes effect.',
      'lt.reasonLabel': 'Reason (recorded in the audit event)',
      'lt.actionConfirmButton': 'Confirm',
      'lt.working': 'Working…',
      'lt.applicability': 'Applicability',
      'lt.content': 'Content',
      'lt.tags': 'Tags',
      'lt.evidenceChain': 'Evidence chain',
      'lt.auditEvents': 'Audit events',

      'overview.database': 'Database',
      'overview.dbSize': 'DB size',
      'overview.fileMissing': 'file missing',
      'overview.dbUpdated': 'DB updated',
      'overview.cliVersion': 'CLI version',
      'overview.cliMissing': 'not detected (check config.bin)',
      'overview.backend': 'Read backend',
      'overview.projectRoot': 'Project root',
      'overview.chip.memories': 'Memories ',
      'overview.chip.projects': 'Projects ',
      'overview.chip.active': 'Active ',
      'overview.chip.archived': 'Archived ',
      'overview.chip.longTerm': 'Long-term memory ',
      'overview.chip.miniSkills': 'Mini-skills ',
      'overview.chip.sessions': 'Sessions ',
      'overview.chip.evidenceCards': 'Evidence cards ',
      'overview.chip.knowledgePages': 'Knowledge pages ',
      'overview.newButton': '+ New memory',
      'overview.searchPlaceholder': 'Search title / entity / type…',
      'overview.matches': 'Matches: ',
      'overview.clearFilters': 'Clear filters',
      'overview.projectsTitle': 'Projects (',
      'overview.noProjects': 'No project memories in Memorix yet',
      'overview.loading': 'Loading Memorix memories…',

      'common.retry': 'Retry',
      'common.noData': 'No data',

      'panel.titleNew': 'Memorix Memory · New',
      'panel.titleLongTerm': 'Memorix Memory · Long-term',
      'panel.titleDetail': 'Memorix Memory · Details',
      'panel.titleOverview': 'Memorix Memory',
      'panel.entryTitle': 'Memorix Memory',
      'panel.entryLabel': 'Memory',
      'panel.loading': 'Loading…',
      'panel.updatedAt': 'Updated at ',
      'panel.refresh': 'Refresh',
      'panel.close': 'Close',

      'age.justNow': 'just now',
      'age.minutes': ' min ago',
      'age.hours': ' h ago',
      'age.days': ' d ago',

      'host.read.storeUnavailable': 'Cannot read the Memorix store (needs Node >= 22.5 or python3)',
      'host.read.longTermUnavailable': 'Cannot read long-term memory (needs Node >= 22.5 or python3)',
      'host.lt.writeDisabled': 'Writes are disabled in this deployment (allowWrite: false)',
      'host.lt.invalidId': 'Invalid long-term memory id',
      'host.lt.invalidAction': 'Invalid action (only qualify / approve / archive are allowed)',
      'host.lt.projectRootMissing': 'Project root not found',
      'host.lt.actionFailed': 'Long-term memory action failed',
      'host.lt.noStateFromCli': 'The CLI did not return the long-term state',
      'host.memory.notFound': 'No memory found with id #{id}',
      'host.memory.invalidId': 'Invalid memory id',
      'host.write.statusDisabled': 'Status writes are disabled in this deployment (allowWrite: false)',
      'host.write.invalidStatus': 'Invalid status (only active / resolved / archived are allowed)',
      'host.write.projectRootMissing': 'Project root for that memory was not found',
      'host.write.failed': 'Failed to write to Memorix',
      'host.write.notUpdated': 'The CLI did not update that memory',
      'host.store.disabled': 'Creating memories is disabled in this deployment (allowStore: false)',
      'host.store.emptyTitle': 'Title cannot be empty',
      'host.store.emptyBody': 'Body cannot be empty',
      'host.store.projectRootMissing': 'Project root for the target project was not found',
      'host.store.noMemoryFromCli': 'The CLI did not return the new memory',
      'host.request.badBody': 'Failed to parse the request body',
      'host.request.unknownAction': 'Unknown action: {action}',
      'host.hint.noProjectMapping': 'missing .project-aliases.json and last-project-root',
      'host.hint.noLastProjectRoot': 'missing last-project-root',
      'host.hint.projectNotRegistered': 'project {projectId} is not in .project-aliases.json',
      'host.hint.cliProject': 'project: {root}',
    }

    /** `{name}` interpolation, mirroring the locale service's own templating. */
    function interpolate(template, params) {
      if (!params) return template
      return template.replace(/\{(\w+)\}/g, (match, name) => (name in params ? String(params[name]) : match))
    }

    /** Bound lookup; the locale service replaces this when it is available. */
    let translate = (key, params) => interpolate(key in zh ? zh[key] : key, params)

    /** True when this namespace owns `key` in either locale. */
    const hasKey = (key) => key in zh || key in en

    /** Translate one namespace key. */
    const t = (key, params) => translate(key, params)

    /** Mounted panels that must re-render when the shell locale changes. */
    const localeSubscribers = new Set()

    /** Ask every mounted panel to re-render. */
    function notifyLocale() {
      for (const bump of Array.from(localeSubscribers)) bump()
    }

    /** Re-render the calling panel whenever the shell locale changes. */
    function useLocaleTick() {
      const [, bump] = React.useReducer((n) => n + 1, 0)
      React.useEffect(() => {
        localeSubscribers.add(bump)
        return () => { localeSubscribers.delete(bump) }
      }, [])
    }

    /** Localized diagnostic for one host response: `code` wins, its message is the fallback. */
    function hostError(res, fallbackKey) {
      const detail = res && typeof res.detail === 'string' && res.detail !== '' ? '\n' + res.detail : ''
      const hint = res && typeof res.hintCode === 'string' && hasKey('host.' + res.hintCode)
        ? '\n' + t('host.' + res.hintCode, res.hintParams)
        : ''
      if (res && typeof res.code === 'string' && hasKey('host.' + res.code)) {
        return t('host.' + res.code, res.params) + hint + detail
      }
      return ((res && res.error) || t(fallbackKey)) + hint + detail
    }

    /** Relative age of an ISO timestamp, rendered under the active locale. */
    function ageLabel(iso, nowIso) {
      if (typeof iso !== 'string' || iso === '') return ''
      const then = Date.parse(iso)
      if (!Number.isFinite(then)) return ''
      const parsedNow = Date.parse(nowIso)
      const seconds = ((Number.isFinite(parsedNow) ? parsedNow : Date.now()) - then) / 1000
      if (!Number.isFinite(seconds) || seconds < 0) return ''
      if (seconds < 60) return t('age.justNow')
      if (seconds < 3600) return String(Math.floor(seconds / 60)) + t('age.minutes')
      if (seconds < 86400) return String(Math.floor(seconds / 3600)) + t('age.hours')
      return String(Math.floor(seconds / 86400)) + t('age.days')
    }

    const STYLE_ID = 'dsh-memorix-panel/panel.css'
    const CSS = `
.mxov-copy{display:inline-flex;align-items:center;justify-content:center;height:18px;min-width:18px;padding:0 5px;margin-left:6px;border:.5px solid var(--dsw-alias-border-l2);border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer;font-size:10px;line-height:1;font-family:var(--dsw-font-family);vertical-align:middle;}
.mxov-copy:hover{border-color:var(--dsw-alias-border-l3);color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover);}
.mxov-copy[data-done=true]{border-color:transparent;background:var(--dsw-alias-state-success-primary);color:var(--dsw-alias-label-primary-inverted);}
.mxov-entry{display:inline-flex;align-items:center;gap:6px;height:26px;padding:0 8px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font-size:12px;font-family:var(--dsw-font-family);}
.mxov-entry:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);}
#dsh-memorix-panel-root[data-placement=edge] .mxov-entry{position:fixed;right:0;top:50%;transform:translateY(-50%);z-index:2147482000;height:auto;padding:7px 10px;border-top:.5px solid var(--dsw-alias-border-l2);border-bottom:.5px solid var(--dsw-alias-border-l2);border-left:.5px solid var(--dsw-alias-border-l3);border-radius:8px 0 0 8px;background:var(--dsw-alias-bg-layer-1);box-shadow:var(--dsw-shadow-lv3);}
.mxov-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-success-primary);flex:0 0 auto;}
.mxov-dot[data-state=loading]{background:var(--dsw-alias-state-warn-primary);}
.mxov-dot[data-state=error]{background:var(--dsw-alias-state-error-primary);}
.mxov-panel{position:fixed;top:0;right:0;bottom:0;left:auto;margin:0;padding:0;width:clamp(320px,26vw,520px);max-width:95vw;height:auto;max-height:none;border:0;border-left:.5px solid var(--dsw-alias-border-l3);border-radius:0;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);box-shadow:var(--dsw-elevation-prominent,var(--dsw-shadow-lv3));display:flex;flex-direction:column;overflow:hidden;z-index:2147483000;font-family:var(--dsw-font-family);font-size:13px;line-height:20px;}
.mxov-panel[data-variant=tab]{position:relative;inset:auto;width:100%;height:100%;max-width:none;max-height:none;border-left:0;box-shadow:none;z-index:auto;}
.mxov-panel *{box-sizing:border-box;}
.mxov-head{display:flex;align-items:center;gap:8px;min-height:46px;padding:0 10px 0 14px;border-bottom:.5px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);flex:0 0 auto;}
.mxov-title{font-weight:600;font-size:13px;white-space:nowrap;}
.mxov-sub{color:var(--dsw-alias-label-tertiary);font-size:11px;margin-left:auto;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:140px;}
.mxov-btn{height:26px;padding:0 10px;border-radius:8px;border:.5px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font-size:12px;flex:0 0 auto;font-family:var(--dsw-font-family);}
.mxov-btn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);}
.mxov-btn[disabled]{opacity:.5;cursor:default;}
.mxov-btn[data-primary=true]{background:var(--dsw-alias-button-primary-fill);border-color:transparent;color:var(--dsw-alias-label-primary-inverted);}
.mxov-btn[data-primary=true]:hover{background:var(--dsw-alias-button-primary-hover);}
.mxov-body{flex:1 1 auto;overflow-y:auto;padding:12px;scrollbar-width:thin;scrollbar-color:var(--dsw-alias-scrollbar-bg-l2) transparent;}
.mxov-body::-webkit-scrollbar{width:8px;height:8px;}
.mxov-body::-webkit-scrollbar-track{background:transparent;}
.mxov-body::-webkit-scrollbar-thumb{background:var(--dsw-alias-scrollbar-bg-l2);border-radius:4px;}
.mxov-body::-webkit-scrollbar-thumb:hover{background:var(--dsw-alias-scrollbar-hover-l2);}
.mxov-card{border:.5px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);padding:10px 12px;margin-bottom:10px;}
.mxov-kv{display:flex;gap:10px;justify-content:space-between;font-size:12px;padding:3px 0;}
.mxov-k{color:var(--dsw-alias-label-tertiary);white-space:nowrap;}
.mxov-v{color:var(--dsw-alias-label-secondary);text-align:right;word-break:break-all;}
.mxov-chips{display:flex;flex-wrap:wrap;gap:6px;}
.mxov-chip{font-size:11px;padding:2px 8px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);}
.mxov-fchip{font-size:11px;padding:3px 9px;border-radius:999px;border:.5px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font-family:var(--dsw-font-family);}
.mxov-fchip:hover{border-color:var(--dsw-alias-border-l3);color:var(--dsw-alias-label-primary);}
.mxov-fchip[data-on=true]{background:var(--dsw-alias-brand-primary);border-color:transparent;color:var(--dsw-alias-label-primary-inverted);}
.mxov-frow{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-bottom:6px;}
.mxov-flabel{font-size:11px;color:var(--dsw-alias-label-tertiary);margin-right:2px;}
.mxov-sec{font-size:11px;color:var(--dsw-alias-label-tertiary);margin:12px 2px 6px;letter-spacing:.04em;}
.mxov-proj{border:.5px solid var(--dsw-alias-border-l1);border-radius:10px;margin-bottom:8px;overflow:hidden;background:var(--dsw-alias-bg-layer-1);}
.mxov-projhead{display:flex;align-items:center;gap:8px;padding:9px 12px;cursor:pointer;}
.mxov-projhead:hover{background:var(--dsw-alias-interactive-bg-hover);}
.mxov-caret{color:var(--dsw-alias-label-tertiary);font-size:10px;width:10px;flex:0 0 auto;}
.mxov-pname{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
.mxov-pmeta{margin-left:auto;color:var(--dsw-alias-label-tertiary);font-size:11px;white-space:nowrap;flex:0 0 auto;}
.mxov-mem{padding:7px 12px;border-top:.5px solid var(--dsw-alias-border-l1);display:flex;gap:8px;align-items:flex-start;cursor:pointer;}
.mxov-mem:hover{background:var(--dsw-alias-interactive-bg-hover);}
.mxov-mem[data-archived=true] .mxov-memname,.mxov-mem[data-archived=true] .mxov-memmeta{opacity:.55;}
.mxov-memtitle{flex:1 1 auto;min-width:0;}
.mxov-memname{overflow:hidden;text-overflow:ellipsis;}
.mxov-memmeta{color:var(--dsw-alias-label-tertiary);font-size:11px;margin-top:1px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
.mxov-tdot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:5px;vertical-align:middle;background:var(--dsw-alias-label-tertiary);}
.mxov-id{color:var(--dsw-alias-label-dimmed);font-size:10px;flex:0 0 auto;padding-top:2px;}
.mxov-search,.mxov-input,.mxov-textarea{width:100%;padding:6px 10px;border-radius:8px;border:.5px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font-size:12px;font-family:var(--dsw-font-family);}
.mxov-search{height:30px;margin-bottom:8px;}
.mxov-textarea{min-height:72px;resize:vertical;line-height:19px;}
.mxov-search:focus,.mxov-input:focus,.mxov-textarea:focus{outline:none;border-color:var(--dsw-alias-brand-primary);}
.mxov-field{display:block;margin-bottom:9px;}
.mxov-flabel2{display:block;font-size:11px;color:var(--dsw-alias-label-tertiary);margin-bottom:3px;}
.mxov-hint{font-size:11px;color:var(--dsw-alias-label-dimmed);margin-top:3px;line-height:16px;}
.mxov-empty{padding:22px 12px;text-align:center;color:var(--dsw-alias-label-tertiary);font-size:12px;}
.mxov-err{padding:8px 10px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-state-error-primary);font-size:12px;margin-bottom:10px;word-break:break-word;white-space:pre-wrap;}
.mxov-ok{padding:8px 10px;border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-state-success-primary);font-size:12px;margin-bottom:10px;}
.mxov-pre{white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:19px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-1);border:.5px solid var(--dsw-alias-border-l1);border-radius:8px;padding:8px 10px;margin:6px 0;}
.mxov-dtitle{font-weight:600;font-size:14px;line-height:20px;margin:2px 0 8px;}
.mxov-list{margin:4px 0 0;padding-left:18px;}
.mxov-list li{font-size:12px;line-height:19px;color:var(--dsw-alias-label-secondary);word-break:break-word;margin-bottom:3px;}
.mxov-mono{font-family:var(--dsw-font-markdown-code,monospace);font-size:11px;word-break:break-all;}
.mxov-back{display:flex;align-items:center;gap:6px;margin-bottom:8px;}
`

    // Locale keys, resolved at call time by the label helpers below.
    const TYPE_LABEL = {
      'how-it-works': 'type.howItWorks', decision: 'type.decision', gotcha: 'type.gotcha', discovery: 'type.discovery',
      'problem-solution': 'type.fix', 'what-changed': 'type.change', 'why-it-exists': 'type.why',
      'trade-off': 'type.tradeoff', reasoning: 'type.reasoning', probe: 'type.probe', 'session-request': 'type.request',
    }
    const TYPE_ORDER = ['decision', 'discovery', 'how-it-works', 'gotcha', 'problem-solution', 'what-changed', 'why-it-exists', 'trade-off', 'reasoning', 'probe', 'session-request']
    const STATUS_LABEL = { active: 'status.active', resolved: 'status.resolved', archived: 'status.archived' }
    const STATUS_ORDER = ['active', 'resolved', 'archived']
    const TYPE_COLOR = {
      decision: 'var(--dsw-alias-state-business-primary)',
      gotcha: 'var(--dsw-alias-state-warn-primary)',
      discovery: 'var(--dsw-alias-state-success-primary)',
      'problem-solution': 'var(--dsw-alias-state-success-primary)',
      'what-changed': 'var(--dsw-alias-brand-primary)',
      'why-it-exists': 'var(--dsw-alias-brand-primary)',
      'trade-off': 'var(--dsw-alias-state-warn-primary)',
      reasoning: 'var(--dsw-alias-label-secondary)',
      probe: 'var(--dsw-alias-label-dimmed)',
    }
    const STATUS_COLOR = {
      active: 'var(--dsw-alias-state-success-primary)',
      archived: 'var(--dsw-alias-label-dimmed)',
      resolved: 'var(--dsw-alias-state-business-primary)',
    }

    // Durable (long-term) memory vocabulary.
    const LT_STATE_LABEL = { approved: 'lt.state.approved', qualified: 'lt.state.qualified', candidate: 'lt.state.candidate', archived: 'status.archived', superseded: 'lt.state.superseded' }
    const LT_STATE_ORDER = ['approved', 'qualified', 'candidate', 'archived', 'superseded']
    const LT_STATE_COLOR = {
      approved: 'var(--dsw-alias-state-success-primary)',
      qualified: 'var(--dsw-alias-state-business-primary)',
      candidate: 'var(--dsw-alias-state-warn-primary)',
      archived: 'var(--dsw-alias-label-dimmed)',
      superseded: 'var(--dsw-alias-label-dimmed)',
    }
    const LT_SCOPE_LABEL = { user: 'lt.scope.user', project: 'lt.scope.project', team: 'lt.scope.team' }
    const LT_SCOPE_ORDER = ['user', 'project', 'team']
    const LT_KIND_LABEL = { semantic: 'lt.kind.semantic', procedural: 'lt.kind.procedural', episodic: 'lt.kind.episodic' }

    const typeLabel = (type) => (TYPE_LABEL[type] === undefined ? (type || t('type.unknown')) : t(TYPE_LABEL[type]))
    const statusLabel = (s) => (STATUS_LABEL[s] === undefined ? (s || '') : t(STATUS_LABEL[s]))
    const ltStateLabel = (s) => (LT_STATE_LABEL[s] === undefined ? (s || '') : t(LT_STATE_LABEL[s]))
    const ltStateColor = (s) => LT_STATE_COLOR[s] || 'var(--dsw-alias-label-tertiary)'
    const ltScopeLabel = (s) => (LT_SCOPE_LABEL[s] === undefined ? (s || '') : t(LT_SCOPE_LABEL[s]))
    const ltKindLabel = (k) => (LT_KIND_LABEL[k] === undefined ? (k || '') : t(LT_KIND_LABEL[k]))
    const typeColor = (type) => TYPE_COLOR[type] || 'var(--dsw-alias-label-tertiary)'
    const statusColor = (s) => STATUS_COLOR[s] || 'var(--dsw-alias-label-tertiary)'
    const ts = (v) => String(v || '').replace('T', ' ').replace('Z', '')
    const lines = (v) => String(v || '').split('\n').map((x) => x.trim()).filter((x) => x !== '')

    /** Last-resort clipboard write (non-secure context fallback). */
    function legacyCopy(text) {
      try {
        const area = document.createElement('textarea')
        area.value = text
        area.setAttribute('readonly', '')
        area.style.cssText = 'position:fixed;top:0;left:0;opacity:0'
        document.body.appendChild(area)
        area.select()
        const ok = document.execCommand('copy')
        document.body.removeChild(area)
        return ok
      } catch (error) {
        return false
      }
    }

    /**
     * Copy one string (typically a project id) with inline success feedback.
     * Always stops propagation: a click must never toggle the row it sits in.
     */
    function CopyButton(props) {
      const [done, setDone] = React.useState(false)
      const onClick = (event) => {
        if (event !== undefined && typeof event.stopPropagation === 'function') event.stopPropagation()
        const text = String(props.text || '')
        if (text === '') return
        const finish = () => {
          setDone(true)
          window.setTimeout(() => setDone(false), 1200)
        }
        const clipboard = typeof navigator !== 'undefined' ? navigator.clipboard : undefined
        if (clipboard !== undefined && typeof clipboard.writeText === 'function') {
          clipboard.writeText(text).then(finish, () => { if (legacyCopy(text)) finish() })
          return
        }
        if (legacyCopy(text)) finish()
      }
      return h('button', {
        type: 'button',
        className: 'mxov-copy',
        'data-done': done ? 'true' : 'false',
        title: done ? t('copy.copied') : t('copy.copyPrefix') + String(props.text || ''),
        onClick: onClick,
      }, done ? '✓' : t('copy.copy'))
    }

    function fmtBytes(n) {
      if (typeof n !== 'number' || !isFinite(n)) return ''
      if (n < 1024) return n + ' B'
      if (n < 1048576) return (n / 1024).toFixed(1) + ' KB'
      if (n < 1073741824) return (n / 1048576).toFixed(1) + ' MB'
      return (n / 1073741824).toFixed(2) + ' GB'
    }

    /** One panel API call against the host half. */
    function api(action, payload) {
      const body = Object.assign({ action }, payload || {})
      return fetch('/memorix-panel/api', {
        method: 'POST',
        credentials: 'same-origin',
        headers: { 'content-type': 'application/json', accept: 'application/json' },
        body: JSON.stringify(body),
      }).then(async (res) => {
        let parsed
        try {
          parsed = await res.json()
        } catch (e) {
          return { ok: false, error: t('error.badResponse') + res.status + ')' }
        }
        return parsed
      })
    }

    /** Insert this package's stylesheet once. */
    function injectStyle() {
      if (document.querySelector('style[data-plugin-css="' + STYLE_ID + '"]')) return null
      const tag = document.createElement('style')
      tag.dataset.plugin = 'dsh-memorix-panel'
      tag.dataset.pluginCss = STYLE_ID
      tag.textContent = CSS
      document.head.appendChild(tag)
      return () => {
        if (tag.parentNode) tag.parentNode.removeChild(tag)
      }
    }

    /** The panel body: list view, detail view and the new-memory form. */
    function MemorixPanel(props) {
      // Re-render this panel when the shell locale changes.
      useLocaleTick()
      const variant = props.variant
      const [open, setOpen] = React.useState(variant === 'tab')
      const [phase, setPhase] = React.useState('idle')
      const [data, setData] = React.useState(null)
      const [error, setError] = React.useState('')
      const [detailErr, setDetailErr] = React.useState('')
      const [query, setQuery] = React.useState('')
      const [expanded, setExpanded] = React.useState(null)
      const [typeFilter, setTypeFilter] = React.useState([])
      const [statusFilter, setStatusFilter] = React.useState([])
      const [openId, setOpenId] = React.useState(null)
      const [mem, setMem] = React.useState(null)
      const [memPhase, setMemPhase] = React.useState('idle')
      const [writePhase, setWritePhase] = React.useState('idle')
      const [writeTarget, setWriteTarget] = React.useState(null)
      const [writeErr, setWriteErr] = React.useState('')
      const [writeNote, setWriteNote] = React.useState('')
      const [composing, setComposing] = React.useState(false)
      const [stage, setStage] = React.useState('edit')
      const [lt, setLt] = React.useState(null)
      const [ltPhase, setLtPhase] = React.useState('idle')
      const [ltStateFilter, setLtStateFilter] = React.useState([])
      const [ltScopeFilter, setLtScopeFilter] = React.useState([])
      const [ltOpenId, setLtOpenId] = React.useState(null)
      const [ltWritePhase, setLtWritePhase] = React.useState('idle')
      const [ltWriteAction, setLtWriteAction] = React.useState(null)
      const [ltWriteReason, setLtWriteReason] = React.useState(t('reason.panelAction'))
      const [ltWriteErr, setLtWriteErr] = React.useState('')
      const [ltWriteNote, setLtWriteNote] = React.useState('')
      const [form, setForm] = React.useState({ title: '', text: '', type: 'discovery', entity: '', facts: '', concepts: '', files: '', topicKey: '', projectId: '' })

      /** Durable-memory fetch: same lifecycle as the overview refresh. */
      const loadLongTerm = React.useCallback(() => {
        setLtPhase('loading')
        return api('long-term').then((res) => {
          if (!res || res.ok === false) {
            setLt(null)
            setLtPhase('error')
            return
          }
          setLt(res)
          setLtPhase('ready')
        }).catch(() => setLtPhase('error'))
      }, [])

      const load = React.useCallback(() => {
        setPhase('loading')
        setError('')
        return api('overview').then((res) => {
          if (!res || res.ok === false) {
            setData(null); setPhase('error'); setError(hostError(res, 'error.readFailed'))
            return
          }
          setData(res)
          setPhase('ready')
          setExpanded((cur) => cur || (res.projects && res.projects.length ? res.projects[0].id : null))
          setForm((cur) => {
            if (cur.projectId) return cur
            const next = Object.assign({}, cur)
            next.projectId = res.projects && res.projects.length ? res.projects[0].id : ''
            return next
          })
        }).catch((e) => {
          setData(null); setPhase('error'); setError(String((e && e.message) || e))
        })
      }, [])

      /** Refresh both layers (observation list + durable memories). */
      const refreshAll = React.useCallback(() => {
        loadLongTerm()
        return load()
      }, [load, loadLongTerm])

      /** Run one durable-memory transition, then re-read the durable layer. */
      const applyLtAction = React.useCallback((id, action, projectId) => {
        setLtWritePhase('writing')
        setLtWriteErr('')
        setLtWriteNote('')
        const reason = ltWriteReason.trim() || t('reason.panelAction')
        return api('lt-transition', { id: id, verb: action, reason: reason, projectId: projectId || '' }).then((res) => {
          if (!res || res.ok === false) {
            setLtWritePhase('idle')
            setLtWriteErr(hostError(res, 'error.actionFailed'))
            return
          }
          setLtWritePhase('idle')
          setLtWriteAction(null)
          setLtWriteNote(action + t('write.succeeded') + ltStateLabel(res.state))
          loadLongTerm()
        }).catch((e) => { setLtWritePhase('idle'); setLtWriteErr(String((e && e.message) || e)) })
      }, [ltWriteReason, loadLongTerm])

      const openMemory = React.useCallback((id) => {
        setComposing(false); setStage('edit')
        setOpenId(id); setMem(null); setMemPhase('loading'); setDetailErr('')
        setWritePhase('idle'); setWriteTarget(null); setWriteErr(''); setWriteNote('')
        return api('memory', { id }).then((res) => {
          if (!res || res.ok === false) { setMemPhase('error'); setDetailErr(hostError(res, 'error.detailReadFailed')); return }
          setMem(res.memory); setMemPhase('ready')
        }).catch((e) => { setMemPhase('error'); setDetailErr(String((e && e.message) || e)) })
      }, [])

      const applyStatus = React.useCallback((id, status) => {
        setWritePhase('writing'); setWriteErr(''); setWriteNote('')
        return api('set-status', { id, status }).then((res) => {
          if (!res || res.ok === false) {
            setWritePhase('idle')
            setWriteErr(hostError(res, 'error.writeFailed'))
            return
          }
          setWritePhase('idle'); setWriteTarget(null)
          setWriteNote(t('write.updatedTo') + statusLabel(status) + '」 (#' + String(id) + ')')
          openMemory(id)
          load()
        }).catch((e) => { setWritePhase('idle'); setWriteErr(String((e && e.message) || e)) })
      }, [openMemory, load])

      const submitNew = React.useCallback(() => {
        setStage('writing'); setWriteErr(''); setWriteNote('')
        return api('store', {
          title: form.title.trim(),
          text: form.text,
          type: form.type,
          entity: form.entity.trim(),
          facts: lines(form.facts),
          concepts: lines(form.concepts),
          files: lines(form.files),
          topicKey: form.topicKey.trim(),
          projectId: form.projectId,
        }).then((res) => {
          if (!res || res.ok === false) {
            setStage('edit')
            setWriteErr(hostError(res, 'error.writeFailed'))
            return
          }
          setStage('edit'); setComposing(false)
          setForm({ title: '', text: '', type: 'discovery', entity: '', facts: '', concepts: '', files: '', topicKey: '', projectId: form.projectId })
          setWriteNote((res.upserted ? t('write.updated') : t('write.created')) + '#' + String(res.id) + ' 「' + String(res.title || '') + '」')
          openMemory(res.id)
          load()
        }).catch((e) => { setStage('edit'); setWriteErr(String((e && e.message) || e)) })
      }, [form, openMemory, load])

      React.useEffect(() => {
        if (!open) return
        if (phase === 'idle') load()
        if (ltPhase === 'idle') loadLongTerm()
      }, [open, phase, ltPhase, load, loadLongTerm])

      const totals = data && data.totals ? data.totals : null
      const projects = data && data.projects ? data.projects : []
      const q = query.trim().toLowerCase()

      const allTypes = []
      projects.forEach((p) => {
        (p.types || []).forEach((entry) => {
          const hit = allTypes.filter((x) => x.type === entry.type)[0]
          if (hit) hit.count += entry.count
          else allTypes.push({ type: entry.type, count: entry.count })
        })
      })
      allTypes.sort((a, b) => b.count - a.count)

      const passesFilter = (m) => {
        if (typeFilter.length && typeFilter.indexOf(m.type) < 0) return false
        if (statusFilter.length && statusFilter.indexOf(m.status) < 0) return false
        if (q) {
          const hay = (String(m.title || '') + ' ' + String(m.entity || '') + ' ' + String(m.type || '')).toLowerCase()
          if (hay.indexOf(q) < 0) return false
        }
        return true
      }
      const filteredOf = (p) => (p.memories || []).filter(passesFilter)
      const toggle = (arr, setArr, value) => {
        setArr(arr.indexOf(value) >= 0 ? arr.filter((x) => x !== value) : arr.concat([value]))
      }
      const setField = (key, value) => {
        setForm((cur) => { const next = Object.assign({}, cur); next[key] = value; return next })
      }

      const filtersActive = typeFilter.length > 0 || statusFilter.length > 0 || q.length > 0
      const matchCount = projects.reduce((sum, p) => sum + filteredOf(p).length, 0)
      const dotState = phase === 'error' ? 'error' : phase === 'loading' ? 'loading' : 'ok'
      const canSubmit = form.title.trim().length > 0 && form.text.trim().length > 0 && stage !== 'writing'
      const readOnly = data && data.readOnly === true
      const storeAllowed = !data || data.storeAllowed !== false

      function renderRows(rows) {
        return h('div', { className: 'mxov-card' }, rows.filter((r) => r && r.v).map((r, i) => h('div', { className: 'mxov-kv', key: i }, [
          h('span', { className: 'mxov-k', key: 'k' }, r.k),
          h('span', { className: 'mxov-v' + (r.mono ? ' mxov-mono' : ''), key: 'v', title: String(r.v) }, [
            r.v,
            r.copy ? h(CopyButton, { key: 'copy', text: r.copy }) : null,
          ]),
        ])))
      }

      function renderMemory(m, key) {
        return h('div', {
          className: 'mxov-mem',
          key: key,
          'data-archived': m.status === 'archived' ? 'true' : 'false',
          title: t('list.clickForBody'),
          onClick: () => openMemory(m.id),
        }, [
          h('div', { className: 'mxov-memtitle', key: 't' }, [
            h('div', { className: 'mxov-memname', key: 'n' }, [
              h('span', { className: 'mxov-tdot', key: 'd', style: { background: typeColor(m.type) } }),
              String(m.title || t('common.untitled')),
            ]),
            h('div', { className: 'mxov-memmeta', key: 'm' }, [
              h('span', { key: 'ty' }, typeLabel(m.type)),
              ' · ',
              h('span', { key: 'st', style: { color: statusColor(m.status) } }, statusLabel(m.status)),
              ' · ' + ageLabel(m.createdAt, data && data.generatedAt),
              m.entity ? '  ·  ' + m.entity : '',
            ]),
          ]),
          h('span', { className: 'mxov-id', key: 'i' }, '#' + String(m.id)),
        ])
      }

      function renderProject(p) {
        const isOpen = expanded === p.id
          const items = filteredOf(p)
        const projectAge = ageLabel(p.lastAt, data && data.generatedAt)
        const children = [h('div', { className: 'mxov-projhead', key: 'h', onClick: () => setExpanded(isOpen ? null : p.id) }, [
          h('span', { className: 'mxov-caret', key: 'c' }, isOpen ? '▾' : '▸'),
          h('span', { className: 'mxov-pname', key: 'n', title: p.id }, p.id),
          h(CopyButton, { key: 'copy', text: p.id }),
          h('span', { className: 'mxov-pmeta', key: 'm' }, (filtersActive ? items.length + '/' + p.total : String(p.total)) + t('project.meta.itemsDot') + p.active + t('project.meta.active') + (projectAge ? ' · ' + projectAge : '')),
        ])]
        if (isOpen) {
          children.push(h('div', { className: 'mxov-mem', key: 'types', style: { display: 'block', cursor: 'default' } },
            h('div', { className: 'mxov-chips' }, (p.types || []).map((entry, i) => h('span', { className: 'mxov-chip', key: i }, typeLabel(entry.type) + ' ' + String(entry.count))))))
          if (!items.length) children.push(h('div', { className: 'mxov-empty', key: 'e' }, t('list.noMatches')))
          else items.forEach((m, i) => children.push(renderMemory(m, 'm' + String(m.id) + '-' + String(i))))
        }
        return h('div', { className: 'mxov-proj', key: p.id }, children)
      }

      function renderCompose() {
        const back = h('div', { className: 'mxov-back', key: 'back' },
          h('button', { className: 'mxov-btn', onClick: () => { setComposing(false); setStage('edit'); setWriteErr('') } }, t('common.backToList')))
        if (stage === 'confirm') {
          const summary = [
            { k: t('field.title'), v: form.title.trim() },
            { k: t('field.type'), v: typeLabel(form.type) + ' (' + form.type + ')' },
            { k: t('field.entity'), v: form.entity.trim() || 'general' },
            { k: t('field.project'), v: form.projectId || t('common.defaultProject') },
            { k: t('field.bodyLength'), v: String(form.text.length) + t('suffix.chars') },
            { k: t('field.facts'), v: lines(form.facts).length + t('suffix.items') },
            { k: t('field.concepts'), v: lines(form.concepts).length + t('suffix.count') },
            { k: t('field.files'), v: lines(form.files).length + t('suffix.count') },
            { k: 'topicKey', v: form.topicKey.trim() || t('common.autoGenerated') },
          ]
          return h('div', { key: 'c' }, [
            back,
            h('div', { className: 'mxov-dtitle', key: 't' }, t('compose.confirmTitle')),
            renderRows(summary),
            h('div', { className: 'mxov-card', key: 'warn' }, t('compose.confirmWarning')),
            h('div', { className: 'mxov-frow', key: 'a' }, [
              h('button', { className: 'mxov-btn', key: 'ok', 'data-primary': 'true', disabled: stage === 'writing', onClick: submitNew }, t('compose.confirmWrite')),
              h('button', { className: 'mxov-btn', key: 'no', onClick: () => setStage('edit') }, t('common.cancel')),
            ]),
            writeErr ? h('div', { className: 'mxov-err', key: 'e' }, writeErr) : null,
          ])
        }
        const writing = stage === 'writing'
        return h('div', { key: 'c' }, [
          back,
          h('div', { className: 'mxov-dtitle', key: 't' }, writing ? t('compose.writing') : t('compose.title')),
          h('label', { className: 'mxov-field', key: 'f1' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.titleLabel')),
            h('input', { key: 'i', className: 'mxov-input', value: form.title, disabled: writing, placeholder: t('compose.titlePlaceholder'), onChange: (e) => setField('title', e.target.value) }),
          ]),
          h('label', { className: 'mxov-field', key: 'f2' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.bodyLabel')),
            h('textarea', { key: 'i', className: 'mxov-textarea', value: form.text, disabled: writing, placeholder: t('compose.bodyPlaceholder'), onChange: (e) => setField('text', e.target.value) }),
          ]),
          h('div', { className: 'mxov-frow', key: 'f3' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.type'))].concat(
            TYPE_ORDER.map((type, i) => h('button', { key: 't' + i, className: 'mxov-fchip', 'data-on': form.type === type ? 'true' : 'false', disabled: writing, onClick: () => setField('type', type) }, typeLabel(type))))),
          h('label', { className: 'mxov-field', key: 'f4' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.entityLabel')),
            h('input', { key: 'i', className: 'mxov-input', value: form.entity, disabled: writing, onChange: (e) => setField('entity', e.target.value) }),
          ]),
          h('label', { className: 'mxov-field', key: 'f5' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.factsLabel')),
            h('textarea', { key: 'i', className: 'mxov-textarea', value: form.facts, disabled: writing, onChange: (e) => setField('facts', e.target.value) }),
          ]),
          h('label', { className: 'mxov-field', key: 'f6' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.conceptsLabel')),
            h('textarea', { key: 'i', className: 'mxov-textarea', value: form.concepts, disabled: writing, onChange: (e) => setField('concepts', e.target.value) }),
          ]),
          h('label', { className: 'mxov-field', key: 'f7' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.filesLabel')),
            h('textarea', { key: 'i', className: 'mxov-textarea', value: form.files, disabled: writing, onChange: (e) => setField('files', e.target.value) }),
          ]),
          h('label', { className: 'mxov-field', key: 'f8' }, [
            h('span', { className: 'mxov-flabel2', key: 'l' }, t('compose.topicKeyLabel')),
            h('input', { key: 'i', className: 'mxov-input', value: form.topicKey, disabled: writing, placeholder: t('compose.topicKeyPlaceholder'), onChange: (e) => setField('topicKey', e.target.value) }),
          ]),
          projects.length > 1 ? h('div', { className: 'mxov-frow', key: 'f9' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('compose.targetProject'))].concat(
            projects.map((p, i) => h('button', { key: 'p' + i, className: 'mxov-fchip', 'data-on': form.projectId === p.id ? 'true' : 'false', disabled: writing, onClick: () => setField('projectId', p.id) }, p.id)))) : null,
          h('div', { className: 'mxov-frow', key: 'act' }, [
            h('button', { className: 'mxov-btn', key: 'go', 'data-primary': 'true', disabled: !canSubmit, onClick: () => { setStage('confirm'); setWriteErr('') } }, t('compose.next')),
          ]),
          h('div', { className: 'mxov-hint', key: 'hint' }, t('compose.hint')),
          writeErr ? h('div', { className: 'mxov-err', key: 'e' }, writeErr) : null,
        ])
      }

      function renderDetail() {
        const back = h('div', { className: 'mxov-back', key: 'back' },
          h('button', { className: 'mxov-btn', onClick: () => { setOpenId(null); setMem(null); setMemPhase('idle'); setWritePhase('idle'); setWriteTarget(null); setWriteErr(''); setWriteNote('') } }, t('common.backToList')))
        if (memPhase === 'loading') return h('div', { key: 'd' }, [back, h('div', { className: 'mxov-empty', key: 'l' }, t('detail.loadingBody'))])
        if (memPhase === 'error') return h('div', { key: 'd' }, [back, h('div', { className: 'mxov-err', key: 'e' }, detailErr)])
        if (!mem) return h('div', { key: 'd' }, [back])

        const rows = [
          { k: t('field.id'), v: '#' + String(mem.id) },
          { k: t('field.type'), v: typeLabel(mem.type) + ' (' + String(mem.type || '') + ')' },
          { k: t('field.status'), v: statusLabel(mem.status) + ' (' + String(mem.status || '') + ')' },
          { k: t('field.project'), v: mem.projectId || '-', mono: true, copy: mem.projectId },
          { k: t('field.entity'), v: mem.entityName || '-' },
          { k: t('field.valueCategory'), v: mem.valueCategory || '-' },
          { k: t('field.visibility'), v: mem.visibility || '-' },
          { k: t('field.source'), v: mem.source || '-' },
          { k: t('field.tokens'), v: mem.tokens === null || mem.tokens === undefined ? '-' : String(mem.tokens) },
          { k: t('field.created'), v: ts(mem.createdAt) },
          { k: t('field.updated'), v: ts(mem.updatedAt) },
          { k: t('field.revisions'), v: mem.revisionCount === null || mem.revisionCount === undefined ? '-' : String(mem.revisionCount) },
          { k: 'topicKey', v: mem.topicKey || '-', mono: true },
          { k: t('field.session'), v: mem.sessionId || '-', mono: true },
          { k: t('field.admissionState'), v: mem.admissionState || '-' },
        ]

        const statusRow = h('div', { className: 'mxov-frow', key: 'strow' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.status'))].concat(
          STATUS_ORDER.map((s, i) => {
            const cur = mem.status === s
            return h('button', {
              key: 's' + i,
              className: 'mxov-fchip',
              'data-on': cur ? 'true' : 'false',
              disabled: cur || readOnly || writePhase === 'writing',
              title: readOnly ? t('detail.statusDisabled') : '',
              onClick: () => {
                if (cur || readOnly || writePhase === 'writing') return
                setWriteTarget(s); setWriteErr(''); setWriteNote(''); setWritePhase('confirm')
              },
            }, statusLabel(s) + (cur ? t('detail.statusCurrent') : ''))
          })))

        const confirmBlock = (writePhase === 'confirm' && writeTarget) ? h('div', { className: 'mxov-card', key: 'confirm' }, [
          h('div', { key: 't', style: { marginBottom: '8px' } }, t('detail.statusConfirmPrefix') + String(mem.id) + t('detail.statusConfirmFrom') + statusLabel(mem.status) + t('detail.statusConfirmTo') + statusLabel(writeTarget) + t('detail.statusConfirmSuffix')),
          h('div', { className: 'mxov-frow', key: 'a', style: { marginBottom: '0' } }, [
            h('button', { key: 'ok', className: 'mxov-btn', 'data-primary': 'true', onClick: () => applyStatus(mem.id, writeTarget) }, t('detail.statusConfirmButton')),
            h('button', { key: 'no', className: 'mxov-btn', onClick: () => { setWritePhase('idle'); setWriteTarget(null) } }, t('common.cancel')),
          ]),
        ]) : null

        const writeBlock = []
        if (writePhase === 'writing') writeBlock.push(h('div', { className: 'mxov-empty', key: 'w' }, t('compose.writing')))
        if (writeNote) writeBlock.push(h('div', { className: 'mxov-ok', key: 'note' }, writeNote))
        if (writeErr) writeBlock.push(h('div', { className: 'mxov-err', key: 'werr' }, writeErr))

        const body = [back, h('div', { className: 'mxov-dtitle', key: 't' }, [
          h('span', { className: 'mxov-tdot', key: 'd', style: { background: typeColor(mem.type) } }),
          String(mem.title || t('common.untitled')),
        ]), statusRow, confirmBlock].concat(writeBlock)
        body.push(renderRows(rows))
        if (mem.narrative) {
          body.push(h('div', { className: 'mxov-sec', key: 'sn' }, t('field.body')))
          body.push(h('div', { className: 'mxov-pre', key: 'n' }, String(mem.narrative)))
        }
        if (mem.facts && mem.facts.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sf' }, t('detail.section.factsCount') + String(mem.facts.length) + ')'))
          body.push(h('ul', { className: 'mxov-list', key: 'f' }, mem.facts.map((x, i) => h('li', { key: i }, String(x)))))
        }
        if (mem.concepts && mem.concepts.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sc' }, t('field.concepts')))
          body.push(h('div', { className: 'mxov-chips', key: 'c' }, mem.concepts.map((x, i) => h('span', { className: 'mxov-chip', key: i }, String(x)))))
        }
        if (mem.filesModified && mem.filesModified.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sfl' }, t('field.files')))
          body.push(h('ul', { className: 'mxov-list', key: 'fl' }, mem.filesModified.map((x, i) => h('li', { className: 'mxov-mono', key: i }, String(x)))))
        }
        if (mem.relatedCommits && mem.relatedCommits.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'src' }, t('detail.section.commits')))
          body.push(h('div', { className: 'mxov-chips', key: 'rc' }, mem.relatedCommits.map((x, i) => h('span', { className: 'mxov-chip mxov-mono', key: i }, String(x)))))
        }
        if (mem.relatedEntities && mem.relatedEntities.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sre' }, t('detail.section.entities')))
          body.push(h('div', { className: 'mxov-chips', key: 're' }, mem.relatedEntities.map((x, i) => h('span', { className: 'mxov-chip', key: i }, String(x)))))
        }
        return h('div', { key: 'd' }, body)
      }

      // ── durable (long-term) memory views ────────────────────────────────
      const ltAll = (lt && lt.memories) || []
      const ltPasses = (m) => {
        if (ltStateFilter.length && ltStateFilter.indexOf(m.state) < 0) return false
        if (ltScopeFilter.length && ltScopeFilter.indexOf(m.scope) < 0) return false
        return true
      }
      const ltItems = ltAll.filter(ltPasses)

      function renderLongTermRow(m, key) {
        const retired = m.state === 'archived' || m.state === 'superseded'
        return h('div', {
          className: 'mxov-mem',
          key: key,
          'data-archived': retired ? 'true' : 'false',
          title: t('list.clickForDetail'),
          onClick: () => { setLtOpenId(m.id); setLtWritePhase('idle'); setLtWriteAction(null); setLtWriteErr(''); setLtWriteNote('') },
        }, [
          h('div', { className: 'mxov-memtitle', key: 't' }, [
            h('div', { className: 'mxov-memname', key: 'n' }, [
              h('span', { className: 'mxov-tdot', key: 'd', style: { background: ltStateColor(m.state) } }),
              String(m.title || t('common.untitled')),
            ]),
            h('div', { className: 'mxov-memmeta', key: 'm' }, [
              h('span', { key: 's', style: { color: ltStateColor(m.state) } }, ltStateLabel(m.state)),
              ' · ' + ltKindLabel(m.kind),
              ' · ' + ltScopeLabel(m.scope) + ' / ' + String(m.portability || '-'),
              m.originProjectId ? '  ·  ' + m.originProjectId : '',
            ]),
          ]),
          h('span', { className: 'mxov-id', key: 'i' }, 'LT'),
        ])
      }

      function renderLongTermSection() {
        const body = [h('div', { className: 'mxov-sec', key: 'sec' }, t('lt.title') + String(ltAll.length) + ')')]
        if (ltPhase === 'loading' && lt === null) {
          body.push(h('div', { className: 'mxov-empty', key: 'l' }, t('lt.loading')))
          return h('div', { key: 'ltsection' }, body)
        }
        if (ltPhase === 'error') {
          body.push(h('div', { className: 'mxov-err', key: 'e' }, t('lt.loadFailed')))
          return h('div', { key: 'ltsection' }, body)
        }
        if (!ltAll.length) {
          body.push(h('div', { className: 'mxov-empty', key: 'e' }, t('lt.empty')))
          return h('div', { key: 'ltsection' }, body)
        }
        const states = LT_STATE_ORDER.filter((s) => ltAll.some((m) => m.state === s))
        const scopes = LT_SCOPE_ORDER.filter((s) => ltAll.some((m) => m.scope === s))
        body.push(h('div', { className: 'mxov-frow', key: 'fs' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.status'))].concat(
          states.map((s, i) => h('button', {
            key: 's' + i,
            className: 'mxov-fchip',
            'data-on': ltStateFilter.indexOf(s) >= 0 ? 'true' : 'false',
            onClick: () => toggle(ltStateFilter, setLtStateFilter, s),
          }, ltStateLabel(s) + ' ' + String(ltAll.filter((m) => m.state === s).length))))))
        if (scopes.length > 1) {
          body.push(h('div', { className: 'mxov-frow', key: 'fsc' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.scope'))].concat(
            scopes.map((s, i) => h('button', {
              key: 'c' + i,
              className: 'mxov-fchip',
              'data-on': ltScopeFilter.indexOf(s) >= 0 ? 'true' : 'false',
              onClick: () => toggle(ltScopeFilter, setLtScopeFilter, s),
            }, ltScopeLabel(s))))))
        }
        if (!ltItems.length) {
          body.push(h('div', { className: 'mxov-empty', key: 'none' }, t('lt.noMatches')))
        } else {
          body.push(h('div', { className: 'mxov-proj', key: 'box' }, ltItems.map((m, i) => renderLongTermRow(m, 'lt' + String(m.id) + '-' + String(i)))))
        }
        return h('div', { key: 'ltsection' }, body)
      }

      function renderLongTermDetail() {
        const m = ltAll.filter((x) => x.id === ltOpenId)[0]
        const back = h('div', { className: 'mxov-back', key: 'back' },
          h('button', { className: 'mxov-btn', onClick: () => { setLtOpenId(null); setLtWritePhase('idle'); setLtWriteAction(null); setLtWriteErr(''); setLtWriteNote('') } }, t('common.backToList')))
        if (!m) {
          return h('div', { key: 'd' }, [back, h('div', { className: 'mxov-empty', key: 'e' }, t('lt.stale'))])
        }
        const rows = [
          { k: t('field.status'), v: ltStateLabel(m.state) + ' (' + String(m.state) + ')' },
          { k: t('field.scope'), v: ltScopeLabel(m.scope) + ' (' + String(m.scope) + ')' },
          { k: t('lt.portability'), v: String(m.portability || '-') },
          { k: t('field.type'), v: ltKindLabel(m.kind) + ' (' + String(m.kind) + ')' },
          { k: t('field.source'), v: String(m.origin || '-') },
          { k: t('lt.originProject'), v: m.originProjectId || '-', mono: true, copy: m.originProjectId },
          { k: t('field.created'), v: ts(m.createdAt) },
          { k: t('field.updated'), v: ts(m.updatedAt) },
          { k: t('lt.qualifiedAt'), v: m.qualifiedAt ? ts(m.qualifiedAt) : '-' },
          { k: t('lt.approvedAt'), v: m.approvedAt ? ts(m.approvedAt) : '-' },
          { k: t('lt.archivedAt'), v: m.archivedAt ? ts(m.archivedAt) : '-' },
          { k: t('lt.supersededBy'), v: m.supersededBy || '-', mono: true },
          { k: t('lt.accessCount'), v: String(m.accessCount ?? 0) },
          { k: t('lt.evidenceAudit'), v: String(m.evidence.length) + ' / ' + String(m.events.length) },
        ]
        const body = [back, h('div', { className: 'mxov-dtitle', key: 't' }, [
          h('span', { className: 'mxov-tdot', key: 'd', style: { background: ltStateColor(m.state) } }),
          String(m.title || t('common.untitled')),
        ])]
        body.push(h('div', { className: 'mxov-sec', key: 'st' }, t('lt.sectionTitle') + ltStateLabel(m.state)))
        body.push(renderRows(rows))
        const busy = ltWritePhase === 'writing'
        const startAction = (action) => { setLtWriteAction(action); setLtWriteErr(''); setLtWriteNote(''); setLtWritePhase('confirm') }
        const actionButtons = []
        if (m.state === 'candidate') actionButtons.push(h('button', { key: 'q', className: 'mxov-btn', 'data-primary': 'true', disabled: busy, onClick: () => startAction('qualify') }, t('lt.action.qualify')))
        if (m.state === 'qualified') actionButtons.push(h('button', { key: 'a', className: 'mxov-btn', 'data-primary': 'true', disabled: busy, onClick: () => startAction('approve') }, t('lt.action.approve')))
        if (m.state === 'candidate' || m.state === 'qualified' || m.state === 'approved') {
          actionButtons.push(h('button', { key: 'r', className: 'mxov-btn', disabled: busy, onClick: () => startAction('archive') }, t('lt.action.archive')))
        }
        body.push(h('div', { className: 'mxov-sec', key: 'sact' }, t('lt.lifecycle')))
        if (actionButtons.length) body.push(h('div', { className: 'mxov-frow', key: 'acts' }, actionButtons))
        else body.push(h('div', { className: 'mxov-empty', key: 'noact' }, t('lt.retired')))
        if (ltWritePhase === 'confirm' && ltWriteAction) {
          body.push(h('div', { className: 'mxov-card', key: 'ltconfirm' }, [
            h('div', { key: 't', style: { marginBottom: '8px' } }, t('lt.actionConfirmPrefix') + ltWriteAction + t('lt.actionConfirmSuffix')),
            h('label', { className: 'mxov-field', key: 'f', style: { marginBottom: '8px' } }, [
              h('span', { className: 'mxov-flabel2', key: 'l' }, t('lt.reasonLabel')),
              h('input', { key: 'i', className: 'mxov-input', value: ltWriteReason, onChange: (e) => setLtWriteReason(e.target.value) }),
            ]),
            h('div', { className: 'mxov-frow', key: 'a', style: { marginBottom: '0' } }, [
              h('button', { key: 'ok', className: 'mxov-btn', 'data-primary': 'true', disabled: busy, onClick: () => applyLtAction(m.id, ltWriteAction, m.originProjectId) }, t('lt.actionConfirmButton')),
              h('button', { key: 'no', className: 'mxov-btn', onClick: () => { setLtWritePhase('idle'); setLtWriteAction(null) } }, t('common.cancel')),
            ]),
          ]))
        }
        if (busy) body.push(h('div', { className: 'mxov-empty', key: 'ltw' }, t('lt.working')))
        if (ltWriteNote) body.push(h('div', { className: 'mxov-ok', key: 'ltn' }, ltWriteNote))
        if (ltWriteErr) body.push(h('div', { className: 'mxov-err', key: 'lte' }, ltWriteErr))
        if (m.applicability) {
          body.push(h('div', { className: 'mxov-sec', key: 'sa' }, t('lt.applicability')))
          body.push(h('div', { className: 'mxov-pre', key: 'a' }, String(m.applicability)))
        }
        if (m.content) {
          body.push(h('div', { className: 'mxov-sec', key: 'sc' }, t('lt.content')))
          body.push(h('div', { className: 'mxov-pre', key: 'c' }, String(m.content)))
        }
        if (m.facts.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sf' }, t('detail.section.factsCount') + String(m.facts.length) + ')'))
          body.push(h('ul', { className: 'mxov-list', key: 'f' }, m.facts.map((x, i) => h('li', { key: i }, String(x)))))
        }
        if (m.tags.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'stg' }, t('lt.tags')))
          body.push(h('div', { className: 'mxov-chips', key: 'g' }, m.tags.map((x, i) => h('span', { className: 'mxov-chip', key: i }, String(x)))))
        }
        if (m.evidence.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sev' }, t('lt.evidenceChain')))
          body.push(h('ul', { className: 'mxov-list', key: 'ev' }, m.evidence.map((e, i) => h('li', { key: i },
            h('span', { className: 'mxov-mono' }, String(e.kind) + ' / ' + String(e.relation)),
            '  ' + String(e.referenceId || '').slice(0, 60) + (e.createdAt ? '  ·  ' + ts(e.createdAt) : '')))))
        }
        if (m.events.length) {
          body.push(h('div', { className: 'mxov-sec', key: 'sevt' }, t('lt.auditEvents')))
          body.push(h('ul', { className: 'mxov-list', key: 'vt' }, m.events.map((e, i) => h('li', { key: i },
            String(e.kind) + ': ' + String(e.fromState ?? '—') + ' → ' + String(e.toState ?? '—') + '  ·  ' + ts(e.createdAt)))))
        }
        return h('div', { key: 'd' }, body)
      }

      function renderList() {
        const body = []
        const db = data.db || {}
        body.push(renderRows([
          { k: t('overview.database'), v: db.path || '-', mono: true },
          { k: t('overview.dbSize'), v: (db.missing ? t('overview.fileMissing') : fmtBytes(db.sizeBytes) + (db.walSizeBytes ? ' (+WAL ' + fmtBytes(db.walSizeBytes) + ')' : '')) },
          { k: t('overview.dbUpdated'), v: ts(db.updatedAt) },
          { k: t('overview.cliVersion'), v: data.cliVersion || t('overview.cliMissing') },
          { k: t('overview.backend'), v: data.backend || '-' },
          { k: t('overview.projectRoot'), v: data.projectRoot || '-', mono: true },
        ]))
        if (totals) {
          body.push(h('div', { className: 'mxov-card', key: 'totals' }, h('div', { className: 'mxov-chips' }, [
            h('span', { className: 'mxov-chip', key: 'm' }, t('overview.chip.memories') + String(totals.memories)),
            h('span', { className: 'mxov-chip', key: 'p' }, t('overview.chip.projects') + String(totals.projects)),
            h('span', { className: 'mxov-chip', key: 'a' }, t('overview.chip.active') + String(totals.active)),
            h('span', { className: 'mxov-chip', key: 'ar' }, t('overview.chip.archived') + String(totals.archived)),
            h('span', { className: 'mxov-chip', key: 'lt' }, t('overview.chip.longTerm') + String(totals.longTerm)),
            h('span', { className: 'mxov-chip', key: 'ms' }, t('overview.chip.miniSkills') + String(totals.miniSkills)),
            h('span', { className: 'mxov-chip', key: 's' }, t('overview.chip.sessions') + String(totals.sessions)),
            h('span', { className: 'mxov-chip', key: 'e' }, t('overview.chip.evidenceCards') + String(totals.evidenceCards)),
            h('span', { className: 'mxov-chip', key: 'k' }, t('overview.chip.knowledgePages') + String(totals.knowledgePages)),
          ])))
        }
        body.push(renderLongTermSection())
        if (storeAllowed) {
          body.push(h('div', { className: 'mxov-frow', key: 'newrow' }, [
            h('button', { className: 'mxov-btn', key: 'new', 'data-primary': 'true', onClick: () => { setComposing(true); setStage('edit'); setOpenId(null); setWriteErr('') } }, t('overview.newButton')),
            writeNote ? h('span', { key: 'note', style: { fontSize: '11px', color: 'var(--dsw-alias-state-success-primary)' } }, writeNote) : null,
          ]))
        } else if (writeNote) {
          body.push(h('div', { className: 'mxov-ok', key: 'note' }, writeNote))
        }
        if (writeErr) body.push(h('div', { className: 'mxov-err', key: 'werr' }, writeErr))
        body.push(h('input', { key: 'search', className: 'mxov-search', placeholder: t('overview.searchPlaceholder'), value: query, onChange: (e) => setQuery(e.target.value) }))
        body.push(h('div', { className: 'mxov-frow', key: 'ft' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.type'))].concat(
          allTypes.map((entry, i) => h('button', { key: 't' + i, className: 'mxov-fchip', 'data-on': typeFilter.indexOf(entry.type) >= 0 ? 'true' : 'false', onClick: () => toggle(typeFilter, setTypeFilter, entry.type) }, typeLabel(entry.type) + ' ' + String(entry.count))))))
        body.push(h('div', { className: 'mxov-frow', key: 'fs' }, [h('span', { className: 'mxov-flabel', key: 'l' }, t('field.status'))].concat(
          STATUS_ORDER.map((s, i) => h('button', { key: 's' + i, className: 'mxov-fchip', 'data-on': statusFilter.indexOf(s) >= 0 ? 'true' : 'false', onClick: () => toggle(statusFilter, setStatusFilter, s) }, statusLabel(s))))))
        if (filtersActive) {
          body.push(h('div', { className: 'mxov-frow', key: 'fr' }, [
            h('span', { className: 'mxov-flabel', key: 'l' }, t('overview.matches') + String(matchCount) + t('suffix.items')),
            h('button', { key: 'c', className: 'mxov-fchip', onClick: () => { setTypeFilter([]); setStatusFilter([]); setQuery('') } }, t('overview.clearFilters')),
          ]))
        }
        body.push(h('div', { className: 'mxov-sec', key: 'sech' }, t('overview.projectsTitle') + String(projects.length) + ')'))
        if (!projects.length) body.push(h('div', { className: 'mxov-empty', key: 'empty' }, t('overview.noProjects')))
        else projects.forEach((p) => body.push(renderProject(p)))
        return h('div', { key: 'list' }, body)
      }

      function renderBody() {
        if (composing) return renderCompose()
        if (openId !== null) return renderDetail()
        if (ltOpenId !== null) return renderLongTermDetail()
        if (phase === 'loading' && !data) return h('div', { className: 'mxov-empty' }, t('overview.loading'))
        if (phase === 'error' && !data) {
          return h('div', null, [
            h('div', { className: 'mxov-err', key: 'e' }, error),
            h('button', { className: 'mxov-btn', key: 'r', onClick: load }, t('common.retry')),
          ])
        }
        if (!data) return h('div', { className: 'mxov-empty' }, t('common.noData'))
        return renderList()
      }

      const headTitle = composing
        ? t('panel.titleNew')
        : (ltOpenId !== null ? t('panel.titleLongTerm') : (openId !== null ? t('panel.titleDetail') : t('panel.titleOverview')))
      const head = h('div', { className: 'mxov-head', key: 'h' }, [
        h('span', { className: 'mxov-title', key: 't' }, headTitle),
        h('span', { className: 'mxov-sub', key: 's' }, phase === 'loading' ? t('panel.loading') : (data && data.generatedAt ? t('panel.updatedAt') + String(data.generatedAt).slice(11, 19) : '')),
        h('button', { className: 'mxov-btn', key: 'r', onClick: refreshAll, title: t('panel.refresh') }, t('panel.refresh')),
        variant !== 'tab' ? h('button', { className: 'mxov-btn', key: 'c', onClick: () => { setOpen(false); setOpenId(null); setComposing(false); setLtOpenId(null) }, title: t('panel.close') }, t('panel.close')) : null,
      ])
      const body = h('div', { className: 'mxov-body', key: 'b' }, renderBody())

      if (variant === 'tab') {
        return h('div', { className: 'mxov-panel', 'data-variant': 'tab' }, [head, body])
      }

      const panelRef = React.useRef(null)
      React.useEffect(() => {
        const el = panelRef.current
        if (!el || !open) return
        if (typeof el.showPopover === 'function') {
          try { el.showPopover() } catch (e) { /* already open / unsupported */ }
        }
        const onToggle = (e) => {
          if (e && e.newState === 'closed') { setOpen(false); setOpenId(null); setComposing(false); setLtOpenId(null) }
        }
        el.addEventListener('toggle', onToggle)
        return () => {
          el.removeEventListener('toggle', onToggle)
          try { if (typeof el.hidePopover === 'function' && el.matches(':popover-open')) el.hidePopover() } catch (e) { /* detached */ }
        }
      }, [open])

      const entry = h('button', {
        className: 'mxov-entry',
        title: t('panel.titleOverview'),
        onClick: () => setOpen((v) => !v),
      }, [
        h('span', { key: 'd', className: 'mxov-dot', 'data-state': dotState }),
        h('span', { key: 't' }, t('panel.entryLabel')),
        totals ? h('span', { key: 'c' }, String(totals.memories)) : null,
      ])

      return h(React.Fragment, null, [
        open ? null : entry,
        open ? h('div', { ref: panelRef, popover: 'auto', className: 'mxov-panel', 'data-variant': 'floating', key: 'panel' }, [head, body]) : null,
      ])
    }

    /** Tab icon for the better-sidebar workbench. */
    function panelIcon(size) {
      const s = typeof size === 'number' ? size : 16
      return h('svg', { width: s, height: s, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.7, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': 'true' }, [
        h('path', { key: 'a', d: 'M9.5 4.5h5a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2h-5a2 2 0 0 1-2-2v-11a2 2 0 0 1 2-2z' }),
        h('path', { key: 'b', d: 'M10.5 9h3M10.5 12h3M10.5 15h2' }),
      ])
    }

    function apply(ctx) {
      const disposeStyle = injectStyle()

      // Panel copy follows the shell locale. Both dictionaries register under this
      // namespace; a deployment without the locale service keeps the Chinese copy.
      const locale = ctx.get('locale')
      if (locale !== undefined && typeof locale.register === 'function' && typeof locale.bind === 'function') {
        ctx.effect(() => {
          try {
            return locale.register(NS, { zh, en })
          } catch (error) {
            // Another instance of this plugin already owns the namespace.
            return () => {}
          }
        }, 'dsh-memorix-panel: locale dictionaries')
        translate = locale.bind(NS)
        if (typeof ctx.on === 'function') {
          ctx.effect(() => ctx.on('locale/change', notifyLocale), 'dsh-memorix-panel: locale switch')
        }
      }
      if (typeof disposeStyle === 'function') ctx.effect(() => disposeStyle, 'dsh-memorix-panel: styles')

      // Primary seat: a body-level mount that then parks itself INSIDE the
      // session header, immediately right of the shipped "Session 日志"
      // (Session log) button. Doing it by DOM lookup — not by the slot
      // service — keeps it independent of client-composition realms, where a
      // slot registration can silently land in a realm the visible UI never
      // reads. Until a session header exists the entry docks to the right edge
      // instead, and a MutationObserver re-parks it whenever the shell
      // re-renders or the session changes.
      const MOUNT_ID = 'dsh-memorix-panel-root'
      let mountedEdge = false
      if (typeof document !== 'undefined' && document.getElementById(MOUNT_ID) === null) {
        let reactDomClient
        try {
          reactDomClient = require('react-dom/client')
        } catch (error) {
          reactDomClient = undefined
        }
        if (reactDomClient !== undefined && typeof reactDomClient.createRoot === 'function') {
          const container = document.createElement('div')
          container.id = MOUNT_ID
          document.body.appendChild(container)
          const root = reactDomClient.createRoot(container)
          root.render(h(MemorixPanel, { variant: 'edge' }))

          /** The shipped session-log capsule this entry sits beside. */
          const findSessionLogButton = () => {
            const byClass = document.querySelector('button[class*="sessionLogButton"]')
            if (byClass !== null) return byClass
            for (const button of document.querySelectorAll('button')) {
              const label = (button.textContent ?? '').trim()
              if (label === 'Session 日志' || label === 'Session log') return button
            }
            return null
          }
          /** Park the entry beside that capsule, else dock it to the edge. */
          const place = () => {
            const logButton = findSessionLogButton()
            const row = logButton === null ? null : logButton.parentElement
            if (row !== null) {
              if (container.parentElement !== row) row.insertBefore(container, logButton.nextSibling)
              container.dataset.placement = 'header'
            } else if (container.parentElement !== document.body || container.dataset.placement !== 'edge') {
              document.body.appendChild(container)
              container.dataset.placement = 'edge'
            }
          }
          place()
          let frame = null
          const observer = new MutationObserver(() => {
            if (frame !== null) return
            frame = requestAnimationFrame(() => {
              frame = null
              place()
            })
          })
          observer.observe(document.body, { childList: true, subtree: true })

          ctx.effect(() => () => {
            observer.disconnect()
            if (frame !== null) cancelAnimationFrame(frame)
            try {
              root.unmount()
            } catch (error) {
              /* already detached */
            }
            if (container.parentNode !== null) container.parentNode.removeChild(container)
          }, 'dsh-memorix-panel: header entry')
          mountedEdge = true
        }
      }

      // Fallback seat when the body-level mount is unavailable: the shipped
      // session-header utilities (its panel still opens in the browser top
      // layer, so nothing can cover it).
      if (!mountedEdge) {
        const slots = ctx.get('slots')
        if (slots !== undefined && typeof slots.inject === 'function') {
          slots.inject('conversation.session.header.utilities', () => slots.register(
            { name: 'conversation.session.header.utilities', id: 'memorix-memory', order: 40, label: t('panel.entryTitle') },
            () => h(MemorixPanel, { variant: 'floating' }),
          ))
        }
      }

      // Bonus seat: a right-workbench tab in dsh-better-sidebar. It only lands
      // when this plugin instance shares the workbench's service instance
      // (same client-composition realm), so nothing relies on it.
      const betterSidebar = ctx.get('betterSidebar')
      if (betterSidebar !== undefined && typeof betterSidebar.registerTab === 'function') {
        ctx.effect(() => betterSidebar.registerTab({
          id: 'memorix',
          title: () => t('panel.entryTitle'),
          icon: (size) => panelIcon(size),
          order: 60,
          component: () => h(MemorixPanel, { variant: 'tab' }),
        }), 'dsh-memorix-panel: better-sidebar tab')
      }
    }

    exports.apply = apply
    return module.exports
  },
})
